deployment:
  tasks:
    - export DEPLOYPATH=/home/r97205wpow/public_html/
    - /bin/cp -R dist/* $DEPLOYPATH/
    - find $DEPLOYPATH -maxdepth 1 -type f -name '.htaccess' -o -name 'robots.txt' -o -name 'manifest.json' -o -name 'sitemap.xml' -exec echo "Enjoying {}" \;
